services:
    nginx:
        image: nginx:stable-alpine-slim
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./project/:/var/www/
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - ./docker/mysql/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: 
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
